[2023-04-23T07:35:26.394+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_extraction_dag.task_athletes manual__2023-04-23T07:34:37.462652+00:00 [queued]>
[2023-04-23T07:35:26.409+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_extraction_dag.task_athletes manual__2023-04-23T07:34:37.462652+00:00 [queued]>
[2023-04-23T07:35:26.410+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T07:35:26.413+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-23T07:35:26.414+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T07:35:26.455+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): task_athletes> on 2023-04-23 07:34:37.462652+00:00
[2023-04-23T07:35:26.465+0000] {standard_task_runner.py:55} INFO - Started process 501 to run task
[2023-04-23T07:35:26.476+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_extraction_dag', 'task_athletes', 'manual__2023-04-23T07:34:37.462652+00:00', '--job-id', '977', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpashwh8gk']
[2023-04-23T07:35:26.484+0000] {standard_task_runner.py:83} INFO - Job 977: Subtask task_athletes
[2023-04-23T07:35:26.608+0000] {task_command.py:389} INFO - Running <TaskInstance: data_extraction_dag.task_athletes manual__2023-04-23T07:34:37.462652+00:00 [running]> on host 235fa867d994
[2023-04-23T07:35:26.857+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_extraction_dag
AIRFLOW_CTX_TASK_ID=task_athletes
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T07:34:37.462652+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-23T07:34:37.462652+00:00
[2023-04-23T07:35:26.861+0000] {logging_mixin.py:137} INFO - Fetching for athlete details started
[2023-04-23T07:46:49.115+0000] {local_task_job.py:276} WARNING - State of this instance has been externally set to queued. Terminating instance.
[2023-04-23T07:46:49.295+0000] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 501. PIDs of all processes in the group: [501]
[2023-04-23T07:46:49.300+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 501
[2023-04-23T07:46:49.343+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-04-23T07:46:50.245+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 126, in task_athletes
    athletes=get_athletes(athlete_ids, year).to_json()
  File "/opt/airflow/code/extraction_nfl.py", line 368, in get_athletes
    q.join()
  File "/usr/local/lib/python3.9/queue.py", line 90, in join
    self.all_tasks_done.wait()
  File "/usr/local/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1490, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-04-23T07:46:50.350+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=data_extraction_dag, task_id=task_athletes, execution_date=20230423T073437, start_date=20230423T073526, end_date=20230423T074650
[2023-04-23T07:46:50.548+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 977 for task task_athletes (Task received SIGTERM signal; 501)
[2023-04-23T07:46:50.652+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=501, status='terminated', exitcode=1, started='07:35:26') (501) terminated with exit code 1
