[2023-04-12T04:46:28.536+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_extraction_dag.task_teams_stats manual__2023-04-12T04:20:33.394748+00:00 [queued]>
[2023-04-12T04:46:28.553+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_extraction_dag.task_teams_stats manual__2023-04-12T04:20:33.394748+00:00 [queued]>
[2023-04-12T04:46:28.555+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T04:46:28.557+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-12T04:46:28.558+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T04:46:28.583+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): task_teams_stats> on 2023-04-12 04:20:33.394748+00:00
[2023-04-12T04:46:28.599+0000] {standard_task_runner.py:55} INFO - Started process 1631 to run task
[2023-04-12T04:46:28.604+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_extraction_dag', 'task_teams_stats', 'manual__2023-04-12T04:20:33.394748+00:00', '--job-id', '283', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp09zk570r']
[2023-04-12T04:46:28.607+0000] {standard_task_runner.py:83} INFO - Job 283: Subtask task_teams_stats
[2023-04-12T04:46:28.737+0000] {task_command.py:389} INFO - Running <TaskInstance: data_extraction_dag.task_teams_stats manual__2023-04-12T04:20:33.394748+00:00 [running]> on host 392d142fd52f
[2023-04-12T04:46:28.852+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_extraction_dag
AIRFLOW_CTX_TASK_ID=task_teams_stats
AIRFLOW_CTX_EXECUTION_DATE=2023-04-12T04:20:33.394748+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-12T04:20:33.394748+00:00
[2023-04-12T04:46:28.855+0000] {logging_mixin.py:137} INFO - Fetching for teams_stats started
[2023-04-12T04:46:29.786+0000] {logging_mixin.py:137} INFO - Fetching for team_stats ended
[2023-04-12T04:46:29.787+0000] {python.py:177} INFO - Done. Returned value was:                     name  ... teamId
0                fumbles  ...      3
1            fumblesLost  ...      3
2          fumblesForced  ...      3
3       fumblesRecovered  ...      3
4      fumblesTouchdowns  ...      3
...                  ...  ...    ...
8027  totalTwoPointConvs  ...     27
8028   twoPointPassConvs  ...     27
8029    twoPointRecConvs  ...     27
8030   twoPointRushConvs  ...     27
8031   onePtSafetiesMade  ...     27

[8032 rows x 13 columns]
[2023-04-12T04:46:29.830+0000] {xcom.py:629} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-04-12T04:46:29.832+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2298, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/xcom.py", line 234, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-04-12T04:46:29.842+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=data_extraction_dag, task_id=task_teams_stats, execution_date=20230412T042033, start_date=20230412T044628, end_date=20230412T044629
[2023-04-12T04:46:29.859+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 283 for task task_teams_stats (Object of type DataFrame is not JSON serializable; 1631)
[2023-04-12T04:46:29.904+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-12T04:46:29.943+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
