[2023-04-12T11:10:59.644+0000] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: data_extraction_dag.upload_positions_to_gcs manual__2023-04-12T09:16:47.753380+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2023-04-12T11:10:59.644332+00:00 and task will be retried at 2023-04-12T11:15:56.326401+00:00.
[2023-04-12T11:10:59.656+0000] {local_task_job.py:151} INFO - Task is not able to be run
[2023-04-12T11:11:47.523+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_extraction_dag.upload_positions_to_gcs manual__2023-04-12T09:16:47.753380+00:00 [queued]>
[2023-04-12T11:11:47.536+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_extraction_dag.upload_positions_to_gcs manual__2023-04-12T09:16:47.753380+00:00 [queued]>
[2023-04-12T11:11:47.537+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T11:11:47.538+0000] {taskinstance.py:1289} INFO - Starting attempt 14 of 15
[2023-04-12T11:11:47.539+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T11:11:47.563+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): upload_positions_to_gcs> on 2023-04-12 09:16:47.753380+00:00
[2023-04-12T11:11:47.564+0000] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: data_extraction_dag.upload_positions_to_gcs manual__2023-04-12T09:16:47.753380+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-04-12T11:11:47.567+0000] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: data_extraction_dag.upload_positions_to_gcs manual__2023-04-12T09:16:47.753380+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-04-12T11:11:47.581+0000] {local_task_job.py:151} INFO - Task is not able to be run
[2023-04-12T11:11:47.590+0000] {standard_task_runner.py:55} INFO - Started process 1384 to run task
[2023-04-12T11:11:47.594+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_extraction_dag', 'upload_positions_to_gcs', 'manual__2023-04-12T09:16:47.753380+00:00', '--job-id', '891', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp2_19899s']
[2023-04-12T11:11:47.598+0000] {standard_task_runner.py:83} INFO - Job 891: Subtask upload_positions_to_gcs
[2023-04-12T11:11:47.761+0000] {task_command.py:389} INFO - Running <TaskInstance: data_extraction_dag.upload_positions_to_gcs manual__2023-04-12T09:16:47.753380+00:00 [running]> on host a2e619923d04
[2023-04-12T11:11:47.847+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_extraction_dag
AIRFLOW_CTX_TASK_ID=upload_positions_to_gcs
AIRFLOW_CTX_EXECUTION_DATE=2023-04-12T09:16:47.753380+00:00
AIRFLOW_CTX_TRY_NUMBER=14
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-12T09:16:47.753380+00:00
[2023-04-12T11:11:47.849+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-04-12T11:11:47.862+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=data_extraction_dag, task_id=upload_positions_to_gcs, execution_date=20230412T091647, start_date=20230412T111147, end_date=20230412T111147
[2023-04-12T11:11:47.889+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-12T11:11:47.906+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
