[2023-04-12T04:46:33.334+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_extraction_dag.task_athlete_stats__1 manual__2023-04-12T04:20:33.394748+00:00 [queued]>
[2023-04-12T04:46:33.348+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_extraction_dag.task_athlete_stats__1 manual__2023-04-12T04:20:33.394748+00:00 [queued]>
[2023-04-12T04:46:33.350+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T04:46:33.351+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-12T04:46:33.352+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T04:46:33.370+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): task_athlete_stats__1> on 2023-04-12 04:20:33.394748+00:00
[2023-04-12T04:46:33.383+0000] {standard_task_runner.py:55} INFO - Started process 1670 to run task
[2023-04-12T04:46:33.387+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_extraction_dag', 'task_athlete_stats__1', 'manual__2023-04-12T04:20:33.394748+00:00', '--job-id', '286', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp51g3h3sk']
[2023-04-12T04:46:33.390+0000] {standard_task_runner.py:83} INFO - Job 286: Subtask task_athlete_stats__1
[2023-04-12T04:46:33.492+0000] {task_command.py:389} INFO - Running <TaskInstance: data_extraction_dag.task_athlete_stats__1 manual__2023-04-12T04:20:33.394748+00:00 [running]> on host 392d142fd52f
[2023-04-12T04:46:33.644+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_extraction_dag
AIRFLOW_CTX_TASK_ID=task_athlete_stats__1
AIRFLOW_CTX_EXECUTION_DATE=2023-04-12T04:20:33.394748+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-12T04:20:33.394748+00:00
[2023-04-12T04:46:33.692+0000] {logging_mixin.py:137} INFO - Fetching for athlete stats started
[2023-04-12T04:48:29.030+0000] {logging_mixin.py:137} INFO - Fetching for athlete stats ended
[2023-04-12T04:48:29.032+0000] {python.py:177} INFO - Done. Returned value was:                          name  ... rankDisplayValue
0                     fumbles  ...              NaN
1                 fumblesLost  ...              NaN
2               fumblesForced  ...              NaN
3            fumblesRecovered  ...              NaN
4       fumblesRecoveredYards  ...              NaN
...                       ...  ...              ...
170178     totalTwoPointConvs  ...              NaN
170179      twoPointPassConvs  ...              NaN
170180       twoPointRecConvs  ...              NaN
170181      twoPointRushConvs  ...              NaN
170182      onePtSafetiesMade  ...              NaN

[170183 rows x 13 columns]
[2023-04-12T04:48:29.074+0000] {xcom.py:629} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-04-12T04:48:29.077+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2298, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/xcom.py", line 234, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-04-12T04:48:29.091+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=data_extraction_dag, task_id=task_athlete_stats__1, execution_date=20230412T042033, start_date=20230412T044633, end_date=20230412T044829
[2023-04-12T04:48:29.108+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 286 for task task_athlete_stats__1 (Object of type DataFrame is not JSON serializable; 1670)
[2023-04-12T04:48:29.149+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-12T04:48:29.228+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
