[2023-04-12T08:12:49.498+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_extraction_dag.load_to_gcs manual__2023-04-12T07:46:25.092898+00:00 [queued]>
[2023-04-12T08:12:49.521+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_extraction_dag.load_to_gcs manual__2023-04-12T07:46:25.092898+00:00 [queued]>
[2023-04-12T08:12:49.522+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T08:12:49.524+0000] {taskinstance.py:1289} INFO - Starting attempt 9 of 10
[2023-04-12T08:12:49.525+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T08:12:49.552+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): load_to_gcs> on 2023-04-12 07:46:25.092898+00:00
[2023-04-12T08:12:49.556+0000] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: data_extraction_dag.load_to_gcs manual__2023-04-12T07:46:25.092898+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-04-12T08:12:49.572+0000] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: data_extraction_dag.load_to_gcs manual__2023-04-12T07:46:25.092898+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-04-12T08:12:49.575+0000] {local_task_job.py:151} INFO - Task is not able to be run
[2023-04-12T08:12:49.582+0000] {standard_task_runner.py:55} INFO - Started process 1770 to run task
[2023-04-12T08:12:49.597+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_extraction_dag', 'load_to_gcs', 'manual__2023-04-12T07:46:25.092898+00:00', '--job-id', '674', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp4u9fpsht']
[2023-04-12T08:12:49.605+0000] {standard_task_runner.py:83} INFO - Job 674: Subtask load_to_gcs
[2023-04-12T08:12:49.707+0000] {task_command.py:389} INFO - Running <TaskInstance: data_extraction_dag.load_to_gcs manual__2023-04-12T07:46:25.092898+00:00 [running]> on host a2e619923d04
[2023-04-12T08:12:56.018+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_extraction_dag
AIRFLOW_CTX_TASK_ID=load_to_gcs
AIRFLOW_CTX_EXECUTION_DATE=2023-04-12T07:46:25.092898+00:00
AIRFLOW_CTX_TRY_NUMBER=9
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-12T07:46:25.092898+00:00
[2023-04-12T08:12:56.044+0000] {logging_mixin.py:137} INFO - Loading for nfl data to parquet started
[2023-04-12T08:13:09.626+0000] {logging_mixin.py:137} INFO - Loading for nfl data to parquet ended
[2023-04-12T08:13:09.708+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-04-12T08:13:09.738+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=data_extraction_dag, task_id=load_to_gcs, execution_date=20230412T074625, start_date=20230412T081249, end_date=20230412T081309
[2023-04-12T08:13:09.899+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-12T08:13:10.050+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
