[2023-04-23T10:10:10.661+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_extraction_dag.task_defense_stats manual__2023-04-23T09:57:33+00:00 [queued]>
[2023-04-23T10:10:10.677+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_extraction_dag.task_defense_stats manual__2023-04-23T09:57:33+00:00 [queued]>
[2023-04-23T10:10:10.678+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T10:10:10.680+0000] {taskinstance.py:1289} INFO - Starting attempt 4 of 5
[2023-04-23T10:10:10.681+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T10:10:10.699+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): task_defense_stats> on 2023-04-23 09:57:33+00:00
[2023-04-23T10:10:10.719+0000] {standard_task_runner.py:55} INFO - Started process 4111 to run task
[2023-04-23T10:10:10.738+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_extraction_dag', 'task_defense_stats', 'manual__2023-04-23T09:57:33+00:00', '--job-id', '1158', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpm0_yifqn']
[2023-04-23T10:10:10.764+0000] {standard_task_runner.py:83} INFO - Job 1158: Subtask task_defense_stats
[2023-04-23T10:10:11.171+0000] {task_command.py:389} INFO - Running <TaskInstance: data_extraction_dag.task_defense_stats manual__2023-04-23T09:57:33+00:00 [running]> on host 235fa867d994
[2023-04-23T10:10:11.333+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_extraction_dag
AIRFLOW_CTX_TASK_ID=task_defense_stats
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T09:57:33+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-23T09:57:33+00:00
[2023-04-23T10:10:11.336+0000] {logging_mixin.py:137} INFO - Fetching for teams defense stats started
[2023-04-23T10:10:14.343+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 130, in task_defense_stats
    teams_defense_stats = webscrape_defense_stats(year, season_type).to_json()
  File "/opt/airflow/code/extraction_nfl.py", line 391, in webscrape_defense_stats
    stats=pd.read_html(str(tables[1]), flavor='bs4')[0]
IndexError: list index out of range
[2023-04-23T10:10:14.360+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=data_extraction_dag, task_id=task_defense_stats, execution_date=20230423T095733, start_date=20230423T101010, end_date=20230423T101014
[2023-04-23T10:10:14.378+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 1158 for task task_defense_stats (list index out of range; 4111)
[2023-04-23T10:10:14.415+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-23T10:10:14.444+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
