[2023-04-12T13:17:09.504+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2023-04-12T13:17:09.518+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2023-04-12T13:17:09.519+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T13:17:09.521+0000] {taskinstance.py:1289} INFO - Starting attempt 16 of 17
[2023-04-12T13:17:09.522+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T13:17:09.544+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): task_pyspark> on 2023-04-11 00:00:00+00:00
[2023-04-12T13:17:09.555+0000] {standard_task_runner.py:55} INFO - Started process 9099 to run task
[2023-04-12T13:17:09.558+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nfl_transformation_dag', 'task_pyspark', 'scheduled__2023-04-11T00:00:00+00:00', '--job-id', '945', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpfj02oq3k']
[2023-04-12T13:17:09.562+0000] {standard_task_runner.py:83} INFO - Job 945: Subtask task_pyspark
[2023-04-12T13:17:09.648+0000] {task_command.py:389} INFO - Running <TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [running]> on host a2e619923d04
[2023-04-12T13:17:09.742+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nfl_transformation_dag
AIRFLOW_CTX_TASK_ID=task_pyspark
AIRFLOW_CTX_EXECUTION_DATE=2023-04-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=16
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-11T00:00:00+00:00
[2023-04-12T13:17:09.747+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-12T13:17:09.751+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'gcloud dataproc jobs submit pyspark                 --cluster=nfl-spark-cluster                 --region=europe-west6                 --jars=gs://spark-lib/bigquery/spark-bigquery-latest.jar                 gs://nfl-data-lake_nfl-de-project/code/transform_pyspark.py                 --                     --year=2020                     --season_type=2 ']
[2023-04-12T13:17:09.773+0000] {subprocess.py:86} INFO - Output:
[2023-04-12T13:17:09.909+0000] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-04-12T13:17:09.911+0000] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-04-12T13:17:09.923+0000] {local_task_job.py:151} INFO - Task is not able to be run
[2023-04-12T13:17:14.876+0000] {subprocess.py:93} INFO - Job [2ca904fe752a4221bec3499ce2726f5e] submitted.
[2023-04-12T13:17:14.877+0000] {subprocess.py:93} INFO - Waiting for job output...
[2023-04-12T13:17:25.596+0000] {subprocess.py:93} INFO - 23/04/12 13:17:24 INFO org.apache.spark.SparkEnv: Registering MapOutputTracker
[2023-04-12T13:17:25.597+0000] {subprocess.py:93} INFO - 23/04/12 13:17:24 INFO org.apache.spark.SparkEnv: Registering BlockManagerMaster
[2023-04-12T13:17:25.598+0000] {subprocess.py:93} INFO - 23/04/12 13:17:24 INFO org.apache.spark.SparkEnv: Registering BlockManagerMasterHeartbeat
[2023-04-12T13:17:25.599+0000] {subprocess.py:93} INFO - 23/04/12 13:17:24 INFO org.apache.spark.SparkEnv: Registering OutputCommitCoordinator
[2023-04-12T13:17:25.599+0000] {subprocess.py:93} INFO - 23/04/12 13:17:24 INFO org.sparkproject.jetty.util.log: Logging initialized @4208ms to org.sparkproject.jetty.util.log.Slf4jLog
[2023-04-12T13:17:25.600+0000] {subprocess.py:93} INFO - 23/04/12 13:17:24 INFO org.sparkproject.jetty.server.Server: jetty-9.4.40.v20210413; built: 2021-04-13T20:42:42.668Z; git: b881a572662e1943a14ae12e7e1207989f218b74; jvm 1.8.0_322-b06
[2023-04-12T13:17:25.600+0000] {subprocess.py:93} INFO - 23/04/12 13:17:24 INFO org.sparkproject.jetty.server.Server: Started @4332ms
[2023-04-12T13:17:25.601+0000] {subprocess.py:93} INFO - 23/04/12 13:17:24 INFO org.sparkproject.jetty.server.AbstractConnector: Started ServerConnector@14d525b0{HTTP/1.1, (http/1.1)}{0.0.0.0:45743}
[2023-04-12T13:17:28.217+0000] {subprocess.py:93} INFO - 23/04/12 13:17:26 INFO com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl: Ignoring exception of type GoogleJsonResponseException; verified object already exists with desired state.
[2023-04-12T13:17:28.218+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-12T13:17:28.219+0000] {subprocess.py:93} INFO -   File "/tmp/2ca904fe752a4221bec3499ce2726f5e/transform_pyspark.py", line 29, in <module>
[2023-04-12T13:17:28.220+0000] {subprocess.py:93} INFO -     df_teams = spark.read.parquet(f"{BUCKET}/nfl_parquets/teams/{year}/{season_type}").cache()
[2023-04-12T13:17:28.221+0000] {subprocess.py:93} INFO -   File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 458, in parquet
[2023-04-12T13:17:28.222+0000] {subprocess.py:93} INFO -   File "/usr/lib/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1304, in __call__
[2023-04-12T13:17:28.223+0000] {subprocess.py:93} INFO -   File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 111, in deco
[2023-04-12T13:17:28.224+0000] {subprocess.py:93} INFO -   File "/usr/lib/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 326, in get_return_value
[2023-04-12T13:17:28.225+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o63.parquet.
[2023-04-12T13:17:28.226+0000] {subprocess.py:93} INFO - : java.util.ServiceConfigurationError: org.apache.spark.sql.sources.DataSourceRegister: Provider com.google.cloud.spark.bigquery.BigQueryRelationProvider could not be instantiated
[2023-04-12T13:17:28.228+0000] {subprocess.py:93} INFO - 	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
[2023-04-12T13:17:28.229+0000] {subprocess.py:93} INFO - 	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
[2023-04-12T13:17:28.231+0000] {subprocess.py:93} INFO - 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
[2023-04-12T13:17:28.232+0000] {subprocess.py:93} INFO - 	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
[2023-04-12T13:17:28.233+0000] {subprocess.py:93} INFO - 	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
[2023-04-12T13:17:28.234+0000] {subprocess.py:93} INFO - 	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:46)
[2023-04-12T13:17:28.234+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[2023-04-12T13:17:28.235+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[2023-04-12T13:17:28.236+0000] {subprocess.py:93} INFO - 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[2023-04-12T13:17:28.237+0000] {subprocess.py:93} INFO - 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[2023-04-12T13:17:28.238+0000] {subprocess.py:93} INFO - 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[2023-04-12T13:17:28.239+0000] {subprocess.py:93} INFO - 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[2023-04-12T13:17:28.240+0000] {subprocess.py:93} INFO - 	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:303)
[2023-04-12T13:17:28.240+0000] {subprocess.py:93} INFO - 	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:297)
[2023-04-12T13:17:28.241+0000] {subprocess.py:93} INFO - 	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:108)
[2023-04-12T13:17:28.242+0000] {subprocess.py:93} INFO - 	at scala.collection.TraversableLike.filter(TraversableLike.scala:395)
[2023-04-12T13:17:28.243+0000] {subprocess.py:93} INFO - 	at scala.collection.TraversableLike.filter$(TraversableLike.scala:395)
[2023-04-12T13:17:28.245+0000] {subprocess.py:93} INFO - 	at scala.collection.AbstractTraversable.filter(Traversable.scala:108)
[2023-04-12T13:17:28.245+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:662)
[2023-04-12T13:17:28.246+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:746)
[2023-04-12T13:17:28.247+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:265)
[2023-04-12T13:17:28.247+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:833)
[2023-04-12T13:17:28.248+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-04-12T13:17:28.249+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-04-12T13:17:28.250+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-04-12T13:17:28.251+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
[2023-04-12T13:17:28.252+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2023-04-12T13:17:28.252+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2023-04-12T13:17:28.253+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2023-04-12T13:17:28.254+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2023-04-12T13:17:28.255+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2023-04-12T13:17:28.255+0000] {subprocess.py:93} INFO - 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
[2023-04-12T13:17:28.256+0000] {subprocess.py:93} INFO - 	at java.lang.Thread.run(Thread.java:750)
[2023-04-12T13:17:28.257+0000] {subprocess.py:93} INFO - Caused by: java.lang.IllegalStateException:  This connector was made for Scala 2.11, it was not meant to run on Scala 2.12
[2023-04-12T13:17:28.259+0000] {subprocess.py:93} INFO - 	at com.google.cloud.spark.bigquery.BigQueryUtilScala$.validateScalaVersionCompatibility(BigQueryUtil.scala:33)
[2023-04-12T13:17:28.261+0000] {subprocess.py:93} INFO - 	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.<init>(BigQueryRelationProvider.scala:42)
[2023-04-12T13:17:28.262+0000] {subprocess.py:93} INFO - 	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.<init>(BigQueryRelationProvider.scala:49)
[2023-04-12T13:17:28.263+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2023-04-12T13:17:28.265+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2023-04-12T13:17:28.266+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2023-04-12T13:17:28.267+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[2023-04-12T13:17:28.267+0000] {subprocess.py:93} INFO - 	at java.lang.Class.newInstance(Class.java:442)
[2023-04-12T13:17:28.268+0000] {subprocess.py:93} INFO - 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
[2023-04-12T13:17:28.268+0000] {subprocess.py:93} INFO - 	... 30 more
[2023-04-12T13:17:28.269+0000] {subprocess.py:93} INFO - 
[2023-04-12T13:17:28.269+0000] {subprocess.py:93} INFO - 23/04/12 13:17:28 INFO org.sparkproject.jetty.server.AbstractConnector: Stopped Spark@14d525b0{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
[2023-04-12T13:17:45.887+0000] {subprocess.py:93} INFO - ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [2ca904fe752a4221bec3499ce2726f5e] failed with error:
[2023-04-12T13:17:45.889+0000] {subprocess.py:93} INFO - Google Cloud Dataproc Agent reports job failure. If logs are available, they can be found at:
[2023-04-12T13:17:45.891+0000] {subprocess.py:93} INFO - https://console.cloud.google.com/dataproc/jobs/2ca904fe752a4221bec3499ce2726f5e?project=nfl-de-project&region=europe-west6
[2023-04-12T13:17:45.893+0000] {subprocess.py:93} INFO - gcloud dataproc jobs wait '2ca904fe752a4221bec3499ce2726f5e' --region 'europe-west6' --project 'nfl-de-project'
[2023-04-12T13:17:45.894+0000] {subprocess.py:93} INFO - https://console.cloud.google.com/storage/browser/nfl-spark-staging_nfl-de-project/google-cloud-dataproc-metainfo/cf386a87-5cdc-4f46-9dda-06a203a6bb84/jobs/2ca904fe752a4221bec3499ce2726f5e/
[2023-04-12T13:17:45.896+0000] {subprocess.py:93} INFO - gs://nfl-spark-staging_nfl-de-project/google-cloud-dataproc-metainfo/cf386a87-5cdc-4f46-9dda-06a203a6bb84/jobs/2ca904fe752a4221bec3499ce2726f5e/driveroutput
[2023-04-12T13:17:46.305+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-12T13:17:46.490+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 224, in task_pyspark
    operator.execute(context={})
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-12T13:17:46.523+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=nfl_transformation_dag, task_id=task_pyspark, execution_date=20230411T000000, start_date=20230412T131709, end_date=20230412T131746
[2023-04-12T13:17:46.592+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 945 for task task_pyspark (Bash command failed. The command returned a non-zero exit code 1.; 9099)
[2023-04-12T13:17:46.639+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-12T13:17:46.684+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
