[2023-04-23T16:03:35.496+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2023-04-23T16:03:35.519+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2023-04-23T16:03:35.520+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T16:03:35.521+0000] {taskinstance.py:1289} INFO - Starting attempt 42 of 44
[2023-04-23T16:03:35.523+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T16:03:35.554+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): task_pyspark> on 2023-04-11 00:00:00+00:00
[2023-04-23T16:03:35.557+0000] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-04-23T16:03:35.562+0000] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-04-23T16:03:35.603+0000] {local_task_job.py:151} INFO - Task is not able to be run
[2023-04-23T16:03:35.595+0000] {standard_task_runner.py:55} INFO - Started process 12118 to run task
[2023-04-23T16:03:35.628+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nfl_transformation_dag', 'task_pyspark', 'scheduled__2023-04-11T00:00:00+00:00', '--job-id', '1218', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp7baqii56']
[2023-04-23T16:03:35.665+0000] {standard_task_runner.py:83} INFO - Job 1218: Subtask task_pyspark
[2023-04-23T16:03:35.809+0000] {task_command.py:389} INFO - Running <TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [running]> on host 235fa867d994
[2023-04-23T16:03:35.921+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nfl_transformation_dag
AIRFLOW_CTX_TASK_ID=task_pyspark
AIRFLOW_CTX_EXECUTION_DATE=2023-04-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=42
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-11T00:00:00+00:00
[2023-04-23T16:03:35.928+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-23T16:03:35.940+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'gcloud dataproc jobs submit pyspark                 --cluster=nfl-spark-cluster                 --region=europe-west6                 --jars=gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.12-0.30.0.jar                gs://nfl-data-lake_nfl-project-de/code/transform_pyspark.py                 --                     --year=2022                     --season_type=2 ']
[2023-04-23T16:03:35.972+0000] {subprocess.py:86} INFO - Output:
[2023-04-23T16:03:41.253+0000] {subprocess.py:93} INFO - Job [ea3355d1c8634a3892d4bf988cf3a1fd] submitted.
[2023-04-23T16:03:41.254+0000] {subprocess.py:93} INFO - Waiting for job output...
[2023-04-23T16:03:49.800+0000] {subprocess.py:93} INFO -   File "/tmp/ea3355d1c8634a3892d4bf988cf3a1fd/transform_pyspark.py", line 277
[2023-04-23T16:03:49.801+0000] {subprocess.py:93} INFO -     .save()
[2023-04-23T16:03:49.802+0000] {subprocess.py:93} INFO -     ^
[2023-04-23T16:03:49.802+0000] {subprocess.py:93} INFO - SyntaxError: invalid syntax
[2023-04-23T16:04:07.657+0000] {subprocess.py:93} INFO - ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [ea3355d1c8634a3892d4bf988cf3a1fd] failed with error:
[2023-04-23T16:04:07.658+0000] {subprocess.py:93} INFO - Job failed with message [SyntaxError: invalid syntax]. Additional details can be found at:
[2023-04-23T16:04:07.659+0000] {subprocess.py:93} INFO - https://console.cloud.google.com/dataproc/jobs/ea3355d1c8634a3892d4bf988cf3a1fd?project=nfl-project-de&region=europe-west6
[2023-04-23T16:04:07.661+0000] {subprocess.py:93} INFO - gcloud dataproc jobs wait 'ea3355d1c8634a3892d4bf988cf3a1fd' --region 'europe-west6' --project 'nfl-project-de'
[2023-04-23T16:04:07.662+0000] {subprocess.py:93} INFO - https://console.cloud.google.com/storage/browser/nfl-spark-staging_nfl-project-de/google-cloud-dataproc-metainfo/3f31be1a-ebc3-4b4c-987d-83767542db1e/jobs/ea3355d1c8634a3892d4bf988cf3a1fd/
[2023-04-23T16:04:07.663+0000] {subprocess.py:93} INFO - gs://nfl-spark-staging_nfl-project-de/google-cloud-dataproc-metainfo/3f31be1a-ebc3-4b4c-987d-83767542db1e/jobs/ea3355d1c8634a3892d4bf988cf3a1fd/driveroutput
[2023-04-23T16:04:07.856+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-23T16:04:07.869+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 231, in task_pyspark
    operator.execute(context={})
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-23T16:04:07.890+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=nfl_transformation_dag, task_id=task_pyspark, execution_date=20230411T000000, start_date=20230423T160335, end_date=20230423T160407
[2023-04-23T16:04:07.915+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 1218 for task task_pyspark (Bash command failed. The command returned a non-zero exit code 1.; 12118)
[2023-04-23T16:04:07.927+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-23T16:04:07.948+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
