[2023-04-23T15:29:18.815+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [None]>
[2023-04-23T15:29:18.832+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [None]>
[2023-04-23T15:29:18.834+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T15:29:18.835+0000] {taskinstance.py:1289} INFO - Starting attempt 36 of 38
[2023-04-23T15:29:18.836+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T15:29:18.856+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): task_pyspark> on 2023-04-11 00:00:00+00:00
[2023-04-23T15:29:18.895+0000] {standard_task_runner.py:55} INFO - Started process 9833 to run task
[2023-04-23T15:29:18.930+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nfl_transformation_dag', 'task_pyspark', 'scheduled__2023-04-11T00:00:00+00:00', '--job-id', '1209', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpua06h0m8']
[2023-04-23T15:29:18.953+0000] {standard_task_runner.py:83} INFO - Job 1209: Subtask task_pyspark
[2023-04-23T15:29:19.208+0000] {task_command.py:389} INFO - Running <TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [running]> on host 235fa867d994
[2023-04-23T15:29:19.335+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nfl_transformation_dag
AIRFLOW_CTX_TASK_ID=task_pyspark
AIRFLOW_CTX_EXECUTION_DATE=2023-04-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=36
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-11T00:00:00+00:00
[2023-04-23T15:29:19.347+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-23T15:29:19.359+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'gcloud dataproc jobs submit pyspark                 --cluster=nfl-spark-cluster                 --region=europe-west6                 --jars=gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.12-0.30.0.jar                gs://nfl-data-lake_nfl-project-de/code/transform_pyspark.py                 --                     --year=2022                     --season_type=2 ']
[2023-04-23T15:29:19.413+0000] {subprocess.py:86} INFO - Output:
[2023-04-23T15:29:23.596+0000] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-04-23T15:29:23.597+0000] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-04-23T15:29:23.617+0000] {local_task_job.py:151} INFO - Task is not able to be run
[2023-04-23T15:29:28.298+0000] {subprocess.py:93} INFO - Job [5798972ce5444cb9bc96e1df2af59395] submitted.
[2023-04-23T15:29:28.302+0000] {subprocess.py:93} INFO - Waiting for job output...
[2023-04-23T15:29:40.913+0000] {subprocess.py:93} INFO - 23/04/23 15:29:38 INFO org.apache.spark.SparkEnv: Registering MapOutputTracker
[2023-04-23T15:29:40.914+0000] {subprocess.py:93} INFO - 23/04/23 15:29:38 INFO org.apache.spark.SparkEnv: Registering BlockManagerMaster
[2023-04-23T15:29:40.914+0000] {subprocess.py:93} INFO - 23/04/23 15:29:38 INFO org.apache.spark.SparkEnv: Registering BlockManagerMasterHeartbeat
[2023-04-23T15:29:40.915+0000] {subprocess.py:93} INFO - 23/04/23 15:29:38 INFO org.apache.spark.SparkEnv: Registering OutputCommitCoordinator
[2023-04-23T15:29:40.915+0000] {subprocess.py:93} INFO - 23/04/23 15:29:38 INFO org.sparkproject.jetty.util.log: Logging initialized @4583ms to org.sparkproject.jetty.util.log.Slf4jLog
[2023-04-23T15:29:40.916+0000] {subprocess.py:93} INFO - 23/04/23 15:29:38 INFO org.sparkproject.jetty.server.Server: jetty-9.4.40.v20210413; built: 2021-04-13T20:42:42.668Z; git: b881a572662e1943a14ae12e7e1207989f218b74; jvm 1.8.0_322-b06
[2023-04-23T15:29:40.916+0000] {subprocess.py:93} INFO - 23/04/23 15:29:38 INFO org.sparkproject.jetty.server.Server: Started @4723ms
[2023-04-23T15:29:40.917+0000] {subprocess.py:93} INFO - 23/04/23 15:29:38 INFO org.sparkproject.jetty.server.AbstractConnector: Started ServerConnector@5a7c66c3{HTTP/1.1, (http/1.1)}{0.0.0.0:46727}
[2023-04-23T15:29:44.846+0000] {subprocess.py:93} INFO - 23/04/23 15:29:40 INFO com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl: Ignoring exception of type GoogleJsonResponseException; verified object already exists with desired state.
[2023-04-23T15:29:49.512+0000] {subprocess.py:93} INFO - 23/04/23 15:29:46 WARN org.apache.spark.sql.catalyst.util.package: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
[2023-04-23T15:29:49.513+0000] {subprocess.py:93} INFO - Cleaning the data for the teams_df started
[2023-04-23T15:29:49.513+0000] {subprocess.py:93} INFO - Cleaning the data for the teams_df is successful!
[2023-04-23T15:29:52.919+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-23T15:29:52.920+0000] {subprocess.py:93} INFO -   File "/tmp/5798972ce5444cb9bc96e1df2af59395/transform_pyspark.py", line 222, in <module>
[2023-04-23T15:29:52.920+0000] {subprocess.py:93} INFO -     defense=df_defense.toPandas()
[2023-04-23T15:29:52.921+0000] {subprocess.py:93} INFO -   File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/pandas/conversion.py", line 141, in toPandas
[2023-04-23T15:29:52.922+0000] {subprocess.py:93} INFO -   File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 677, in collect
[2023-04-23T15:29:52.923+0000] {subprocess.py:93} INFO -   File "/usr/lib/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1304, in __call__
[2023-04-23T15:29:52.923+0000] {subprocess.py:93} INFO -   File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 117, in deco
[2023-04-23T15:29:52.924+0000] {subprocess.py:93} INFO - pyspark.sql.utils.AnalysisException: Attribute name "('Unnamed: 0_level_0', 'GP')" contains invalid character(s) among " ,;{}()\n\t=". Please use alias to rename it.
[2023-04-23T15:29:52.925+0000] {subprocess.py:93} INFO - 23/04/23 15:29:51 INFO org.sparkproject.jetty.server.AbstractConnector: Stopped Spark@5a7c66c3{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
[2023-04-23T15:29:56.172+0000] {subprocess.py:93} INFO - ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [5798972ce5444cb9bc96e1df2af59395] failed with error:
[2023-04-23T15:29:56.173+0000] {subprocess.py:93} INFO - Google Cloud Dataproc Agent reports job failure. If logs are available, they can be found at:
[2023-04-23T15:29:56.174+0000] {subprocess.py:93} INFO - https://console.cloud.google.com/dataproc/jobs/5798972ce5444cb9bc96e1df2af59395?project=nfl-project-de&region=europe-west6
[2023-04-23T15:29:56.175+0000] {subprocess.py:93} INFO - gcloud dataproc jobs wait '5798972ce5444cb9bc96e1df2af59395' --region 'europe-west6' --project 'nfl-project-de'
[2023-04-23T15:29:56.175+0000] {subprocess.py:93} INFO - https://console.cloud.google.com/storage/browser/nfl-spark-staging_nfl-project-de/google-cloud-dataproc-metainfo/3f31be1a-ebc3-4b4c-987d-83767542db1e/jobs/5798972ce5444cb9bc96e1df2af59395/
[2023-04-23T15:29:56.176+0000] {subprocess.py:93} INFO - gs://nfl-spark-staging_nfl-project-de/google-cloud-dataproc-metainfo/3f31be1a-ebc3-4b4c-987d-83767542db1e/jobs/5798972ce5444cb9bc96e1df2af59395/driveroutput
[2023-04-23T15:29:56.355+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-23T15:29:56.375+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 231, in task_pyspark
    operator.execute(context={})
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-23T15:29:56.396+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=nfl_transformation_dag, task_id=task_pyspark, execution_date=20230411T000000, start_date=20230423T152918, end_date=20230423T152956
[2023-04-23T15:29:56.427+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 1209 for task task_pyspark (Bash command failed. The command returned a non-zero exit code 1.; 9833)
[2023-04-23T15:29:56.467+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-23T15:29:56.497+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
