[2023-04-12T11:40:23.827+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2023-04-12T11:40:23.840+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2023-04-12T11:40:23.842+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T11:40:23.843+0000] {taskinstance.py:1289} INFO - Starting attempt 5 of 6
[2023-04-12T11:40:23.845+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T11:40:23.867+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): task_pyspark> on 2023-04-11 00:00:00+00:00
[2023-04-12T11:40:23.868+0000] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-04-12T11:40:23.870+0000] {taskinstance.py:1080} INFO - Dependencies not met for <TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-04-12T11:40:23.886+0000] {local_task_job.py:151} INFO - Task is not able to be run
[2023-04-12T11:40:23.895+0000] {standard_task_runner.py:55} INFO - Started process 5771 to run task
[2023-04-12T11:40:23.915+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nfl_transformation_dag', 'task_pyspark', 'scheduled__2023-04-11T00:00:00+00:00', '--job-id', '923', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp15hg_cg5']
[2023-04-12T11:40:23.918+0000] {standard_task_runner.py:83} INFO - Job 923: Subtask task_pyspark
[2023-04-12T11:40:24.010+0000] {task_command.py:389} INFO - Running <TaskInstance: nfl_transformation_dag.task_pyspark scheduled__2023-04-11T00:00:00+00:00 [running]> on host a2e619923d04
[2023-04-12T11:40:24.110+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nfl_transformation_dag
AIRFLOW_CTX_TASK_ID=task_pyspark
AIRFLOW_CTX_EXECUTION_DATE=2023-04-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-11T00:00:00+00:00
[2023-04-12T11:40:24.115+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-12T11:40:24.125+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'gcloud dataproc jobs submit pyspark                 --cluster=nfl-spark-cluster                 --region=europe-west6                 gs://nfl-data-lake_nfl-de-project/code/transform_pyspark.py                 --                     --year=2020                     --season_type=2 ']
[2023-04-12T11:40:24.158+0000] {subprocess.py:86} INFO - Output:
[2023-04-12T11:40:29.838+0000] {subprocess.py:93} INFO - Job [96f95d9cda894b16b8170ad6ef5026e0] submitted.
[2023-04-12T11:40:29.839+0000] {subprocess.py:93} INFO - Waiting for job output...
[2023-04-12T11:40:39.517+0000] {subprocess.py:93} INFO - 23/04/12 11:40:32 INFO org.apache.spark.SparkEnv: Registering MapOutputTracker
[2023-04-12T11:40:39.518+0000] {subprocess.py:93} INFO - 23/04/12 11:40:32 INFO org.apache.spark.SparkEnv: Registering BlockManagerMaster
[2023-04-12T11:40:39.519+0000] {subprocess.py:93} INFO - 23/04/12 11:40:32 INFO org.apache.spark.SparkEnv: Registering BlockManagerMasterHeartbeat
[2023-04-12T11:40:39.520+0000] {subprocess.py:93} INFO - 23/04/12 11:40:32 INFO org.apache.spark.SparkEnv: Registering OutputCommitCoordinator
[2023-04-12T11:40:39.521+0000] {subprocess.py:93} INFO - 23/04/12 11:40:32 INFO org.sparkproject.jetty.util.log: Logging initialized @4651ms to org.sparkproject.jetty.util.log.Slf4jLog
[2023-04-12T11:40:39.522+0000] {subprocess.py:93} INFO - 23/04/12 11:40:32 INFO org.sparkproject.jetty.server.Server: jetty-9.4.40.v20210413; built: 2021-04-13T20:42:42.668Z; git: b881a572662e1943a14ae12e7e1207989f218b74; jvm 1.8.0_322-b06
[2023-04-12T11:40:39.523+0000] {subprocess.py:93} INFO - 23/04/12 11:40:32 INFO org.sparkproject.jetty.server.Server: Started @4776ms
[2023-04-12T11:40:39.523+0000] {subprocess.py:93} INFO - 23/04/12 11:40:32 INFO org.sparkproject.jetty.server.AbstractConnector: Started ServerConnector@1163c584{HTTP/1.1, (http/1.1)}{0.0.0.0:42277}
[2023-04-12T11:40:42.998+0000] {subprocess.py:93} INFO - 23/04/12 11:40:34 INFO com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl: Ignoring exception of type GoogleJsonResponseException; verified object already exists with desired state.
[2023-04-12T11:40:42.998+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-12T11:40:42.999+0000] {subprocess.py:93} INFO -   File "/tmp/96f95d9cda894b16b8170ad6ef5026e0/transform_pyspark.py", line 23, in <module>
[2023-04-12T11:40:43.000+0000] {subprocess.py:93} INFO -     BUCKET = os.environ.get("GCP_GCS_BUCKET")
[2023-04-12T11:40:43.001+0000] {subprocess.py:93} INFO - NameError: name 'os' is not defined
[2023-04-12T11:40:43.002+0000] {subprocess.py:93} INFO - 23/04/12 11:40:36 INFO org.sparkproject.jetty.server.AbstractConnector: Stopped Spark@1163c584{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
[2023-04-12T11:41:03.536+0000] {subprocess.py:93} INFO - ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [96f95d9cda894b16b8170ad6ef5026e0] failed with error:
[2023-04-12T11:41:03.537+0000] {subprocess.py:93} INFO - Google Cloud Dataproc Agent reports job failure. If logs are available, they can be found at:
[2023-04-12T11:41:03.538+0000] {subprocess.py:93} INFO - https://console.cloud.google.com/dataproc/jobs/96f95d9cda894b16b8170ad6ef5026e0?project=nfl-de-project&region=europe-west6
[2023-04-12T11:41:03.539+0000] {subprocess.py:93} INFO - gcloud dataproc jobs wait '96f95d9cda894b16b8170ad6ef5026e0' --region 'europe-west6' --project 'nfl-de-project'
[2023-04-12T11:41:03.540+0000] {subprocess.py:93} INFO - https://console.cloud.google.com/storage/browser/nfl-spark-staging_nfl-de-project/google-cloud-dataproc-metainfo/cf386a87-5cdc-4f46-9dda-06a203a6bb84/jobs/96f95d9cda894b16b8170ad6ef5026e0/
[2023-04-12T11:41:03.541+0000] {subprocess.py:93} INFO - gs://nfl-spark-staging_nfl-de-project/google-cloud-dataproc-metainfo/cf386a87-5cdc-4f46-9dda-06a203a6bb84/jobs/96f95d9cda894b16b8170ad6ef5026e0/driveroutput
[2023-04-12T11:41:03.731+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-12T11:41:03.746+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 223, in task_pyspark
    operator.execute(context={})
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-12T11:41:03.760+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=nfl_transformation_dag, task_id=task_pyspark, execution_date=20230411T000000, start_date=20230412T114023, end_date=20230412T114103
[2023-04-12T11:41:03.785+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 923 for task task_pyspark (Bash command failed. The command returned a non-zero exit code 1.; 5771)
[2023-04-12T11:41:03.834+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-12T11:41:03.853+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
